main: me.tks.playerwarp.PWarp
name: PWarp
version: 2.7
api-version: 1.13
author: The_King_Senne
softdepend: [Multiverse-Core, GriefPrevention, Vault]
commands:
  pwarp:
    description: Main command for playerwarps
    aliases: pw
    usage: "/pw help"
  pwg:
    description: Opens the warp GUI
    aliases: pws
    usage: "/pwg"
  pwwarp:
    description: Warps to a warp
    aliases: pww
    usage: "/pwwarp <warp>"

